from kfp.v2.dsl import component, Artifact, Input


@component(
    base_image="gcr.io/deeplearning-platform-release/sklearn-cpu.0-23",
    packages_to_install=[
        "google-cloud==0.34.0",
        "gcsfs==2021.11.1",
        "google-auth==1.35.0",
        "google-cloud-logging==2.7.0",
    ],
    output_component_file="artifacts/deploy_component.yaml",
)
def model_deploy(endpoint_artifact: Input[Artifact], model_artifact: Input[Artifact]):
    """this function takes the endpoint & model, to deploys model to endpoint

    Args:
        endpoint_artifact (Input[Artifact]): endpoint where model will be deployed
        model_artifact (Input[Artifact]): model generated by automl text model
    """    
    from google.cloud import aiplatform

    model = aiplatform.models.Model(model_artifact.metadata["resourceName"])
    endpoint = aiplatform.Endpoint(endpoint_artifact.metadata["resourceName"])
    endpoint.deploy(model)
